name: Rust CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with: { name: acs_seed_finder-windows-exe, path: target/release/acs_seed_finder.exe }